POST https://localhost:7234/api/todoitems
Content-Type: application/json

{
  "name": "muista hedelmät"
}

###

GET https://localhost:7234/api/todoitems

###

GET https://localhost:7234/health

###

GET https://localhost:7234/info